### ISSUE TITLE
Proposed roadmap for DataArrays revision

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/DataArrays.jl#48]
Here's a list of what I would consider the most important changes to make to this package:
- [ ] Find a better abstraction for iteration than the `Each*` types
- [x] Add an indexing version of `isna`: `isna(da, inds)`
- [ ] Straighten out and/or remove promotion rules
- [ ] Ensure systematic test coverage of codebase
- [x] Get `unique` and `levels` definitions right
- [ ] Clean up `@data` and `@pdata` macros
- [ ] Move `autocor`, `percent_change` and `reldiff` to Stats.jl
- [ ] Remove `databool`, `datafloat` and `dataint`
- [ ] Stop exporting `get_indices`, `index_to_level` and `level_to_index`
- [ ] Stop exporting `getpoolidx`
- [ ] Drop `pdatabool`, `pdatafloat` and `pdataint`
- [ ] Clean up definition of `reorder` / move it to DataFrames.jl
- [ ] Merge existing `rep` functionality into `Base.repeat`
- [ ] Add optional category ordering to `PooledDataArray`
- [ ] Move `xtab` and `xtabs` to Stats
- [ ] Move linalg.jl functions to a separate package
- [ ] Try to find a way to remove `baseval` hack
- [x] Clean up operators code
- [x] Add keyword args to basic statistical functions that must `skipna` or `dropna`
- [ ] Replace all `row*` and `col*` functions with slice-indexing interface
- [ ] Do something with `gl`
